import "@/node_modules/react-modal-video/css/modal-video.css";
import "public/assets/css/bootstrap.css";
import "public/assets/css/color.css";
import "public/assets/css/font-awesome-all.css";
import "public/assets/css/flaticon.css";
import "public/assets/css/style.css";
import "public/assets/css/rtl.css";
import "swiper/css";
// import "swiper/css/navigation"
import "swiper/css/pagination";
import "swiper/css/free-mode";
import { inter, jost } from "@/lib/font";
import Head from "next/head";
import Script from "next/script";


export const metadata = {
  title: "Hydro-Plan IL",
  description: "Generated by create next app",
};

<Head>
<meta charSet="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{metadata.title}</title>
<meta name="description" content={metadata.description} />
{/* Other meta tags, CSS files, or JavaScript can be included here */}
</Head>

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${jost.variable}`}>
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-M955VS30JE"></Script>
<Script id="google-analytics" strategy="afterInteractive">
        {`
           window.dataLayer = window.dataLayer || [];
           function gtag(){dataLayer.push(arguments);}
           gtag('js', new Date());
         
           gtag('config', 'G-M955VS30JE');
        `}
      </Script>
      <body>{children}</body>
    </html>
  );
}
